<?php
	esc_html__('PARAM', 'lab');
	esc_html__('GROUP TYPE', 'lab');
	esc_html__('KEY TYPE', 'lab');
	esc_html__('SITE', 'lab');
	esc_html__('USER FUNCTION', 'lab');
	esc_html__('MISSION', 'lab');
	esc_html__('FUNDING', 'lab');
	esc_html__('EMPLOYER', 'lab');
	esc_html__('LDAP TOKEN', 'lab');
	esc_html__('LDAP HOST', 'lab');
	esc_html__('LDAP BASE', 'lab');
	esc_html__('LDAP LOGIN', 'lab');
	esc_html__('LDAP PASSWORD', 'lab');
	esc_html__('LDAP TLS', 'lab');
	esc_html__('LDAP ENABLE', 'lab');
	esc_html__('USER SECTION CN', 'lab');
	esc_html__('USER SECTION CNU', 'lab');
	esc_html__('OUTGOING MOBILITY', 'lab');
	esc_html__('KEY STATE', 'lab');
	esc_html__('PHD SCHOOL', 'lab');
	esc_html__('OUTGOING MOBILITY STATUS', 'lab');
	esc_html__('THEMATIC', 'lab');
	esc_html__('BUDGET INFO TYPE', 'lab');
	esc_html__('BUDGET FUNDS', 'lab');
	esc_html__('CONTRACT TYPE', 'lab');
	esc_html__('MEAN OF TRANSPORT', 'lab');
	esc_html__('MISSION STATUS', 'lab');
	esc_html__('Chargé de Recherche (CR)', 'lab');
	esc_html__('Directeur de Recherche (DR)', 'lab');
	esc_html__('Equipe', 'lab');
	esc_html__('Aix-Marseille Université (AMU)', 'lab');
	esc_html__('Centre National Recherche Scientifique (CNRS)', 'lab');
	esc_html__('École Centrale de Marseille (ECM)', 'lab');
	esc_html__('Université du Sud-Toulon-Var (USTV)', 'lab');
	esc_html__('Groupe', 'lab');
	esc_html__('Saint-Charles', 'lab');
	esc_html__('Château-Gombert (CMI)', 'lab');
	esc_html__('Luminy', 'lab');
	esc_html__('Maître de Conférences (MCF H)', 'lab');
	esc_html__('Stagiaire (H)', 'lab');
	esc_html__('Professeur (PR)', 'lab');
	esc_html__('ldap.i2m.univ-amu.fr', 'lab');
	esc_html__('mLG4MFS7bKyqVqKoUoNQviVJvTgspdNTHwGPzuDn2', 'lab');
	esc_html__('dc=i2m,dc=univ-amu,dc=fr', 'lab');
	esc_html__('cn=admin', 'lab');
	esc_html__('d5u.4SR:', 'lab');
	esc_html__('true', 'lab');
	esc_html__('AMU', 'lab');
	esc_html__('CNRS', 'lab');
	esc_html__('CIFRE EDF', 'lab');
	esc_html__('USTV', 'lab');
	esc_html__('ECOS Nord', 'lab');
	esc_html__('Chinese Scolarship Council (CSC)', 'lab');
	esc_html__('PostDoctorant (Postdoctoral Researcher)', 'lab');
	esc_html__('true', 'lab');
	esc_html__('CDD Chercheur', 'lab');
	esc_html__('Maître de Conférences (MCF F)', 'lab');
	esc_html__('Technicienne (T)', 'lab');
	esc_html__('Professeure (PR)', 'lab');
	esc_html__('Agente Technique de Recherche et de Formation (AGT)', 'lab');
	esc_html__('Adjointe Technique Recherche et Formation', 'lab');
	esc_html__('Assistante-Ingénieure (AI)', 'lab');
	esc_html__('Adjointe Technique (AJT)', 'lab');
	esc_html__('CDD Chercheuse', 'lab');
	esc_html__('CDD Ingénieur de Recherche', 'lab');
	esc_html__('CDD Ingénieure de Recherche', 'lab');
	esc_html__('Chargée de Recherche (CR)', 'lab');
	esc_html__('Directrice de Recherche (DR)', 'lab');
	esc_html__('Directrice de Recherche Émérite (DREM)', 'lab');
	esc_html__('Ingénieure d’Études (IE)', 'lab');
	esc_html__('Ingénieur d’Études (IGE)', 'lab');
	esc_html__('Ingénieure d’Études (IGE)', 'lab');
	esc_html__('Assistant-Ingénieur (ASI)', 'lab');
	esc_html__('Assistante-Ingénieure (ASI)', 'lab');
	esc_html__('Ingénieure de Recherche (IR)', 'lab');
	esc_html__('Ingénieur de Recherche (IGR)', 'lab');
	esc_html__('Ingénieure de Recherche (IGR)', 'lab');
	esc_html__('Chargé de Recherche Émérite (CREM)', 'lab');
	esc_html__('Chargée de Recherche Émérite (CREM)', 'lab');
	esc_html__('Maître de Conférences Émérite (MCFEM H)', 'lab');
	esc_html__('Maître de Conférences Émérite (MCFEM F)', 'lab');
	esc_html__('Membre Associée', 'lab');
	esc_html__('Doctorante (Phd Student)', 'lab');
	esc_html__('PostDoctorante (Postdoctoral Researcher)', 'lab');
	esc_html__('Professeure Émérite (PREM)', 'lab');
	esc_html__('Technicien (TCH)', 'lab');
	esc_html__('Technicienne (TCH)', 'lab');
	esc_html__('I2M', 'lab');
	esc_html__('AMU (AMIDEX)', 'lab');
	esc_html__('Stagiaire (F)', 'lab');
	esc_html__('I2M', 'lab');
	esc_html__('Ressources Propres', 'lab');
	esc_html__('Visiteur (visiting researcher)', 'lab');
	esc_html__('Visiteuse (visiting researcher)', 'lab');
	esc_html__('Saint Jérôme', 'lab');
	esc_html__('CT.C (H)', 'lab');
	esc_html__('IUT', 'lab');
	esc_html__('Doctorant (Phd Student)', 'lab');
	esc_html__('ENS Paris-Saclay', 'lab');
	esc_html__('ENS Rennes', 'lab');
	esc_html__('ENS Paris Ulm', 'lab');
	esc_html__('ENS', 'lab');
	esc_html__('ENS Lyon', 'lab');
	esc_html__('ENS', 'lab');
	esc_html__('ENS Paris Ulm', 'lab');
	esc_html__('ENS Lyon', 'lab');
	esc_html__('ENS Paris-Saclay', 'lab');
	esc_html__('ENS Rennes', 'lab');
	esc_html__('ERC ICHAOS', 'lab');
	esc_html__('ERC HOLOGRAM', 'lab');
	esc_html__('Attaché Temporaire d’Enseignement et de Recherche (ATER)', 'lab');
	esc_html__('Clef', 'lab');
	esc_html__('Badge', 'lab');
	esc_html__('ECM', 'lab');
	esc_html__('IUT', 'lab');
	esc_html__('ANR SAMARA', 'lab');
	esc_html__('CNRS (projet Axonogénèse)', 'lab');
	esc_html__('41', 'lab');
	esc_html__('07', 'lab');
	esc_html__('10', 'lab');
	esc_html__('25', 'lab');
	esc_html__('26', 'lab');
	esc_html__('27', 'lab');
	esc_html__('25', 'lab');
	esc_html__('CIFRE Renault', 'lab');
	esc_html__('CIFRE S4M', 'lab');
	esc_html__('CD IRSN', 'lab');
	esc_html__('AMU (ED184)', 'lab');
	esc_html__('AMU (ILCB)', 'lab');
	esc_html__('AMU (CEA)', 'lab');
	esc_html__('Ingénieur de Recherche (IR)', 'lab');
	esc_html__('Ingénieur d’Études (IE)', 'lab');
	esc_html__('Assistant-Ingénieur (AI)', 'lab');
	esc_html__('ok', 'lab');
	esc_html__('lost', 'lab');
	esc_html__('broken', 'lab');
	esc_html__('MESRI', 'lab');
	esc_html__('Groupe Renault', 'lab');
	esc_html__('EDF Chatou', 'lab');
	esc_html__('Paris-Chatou', 'lab');
	esc_html__('AMU/ENS', 'lab');
	esc_html__('Technicien (T)', 'lab');
	esc_html__('ED184', 'lab');
	esc_html__('ED62', 'lab');
	esc_html__('ECM/INRIA', 'lab');
	esc_html__('AMU (AMIDEX/EUROFUSION)', 'lab');
	esc_html__('CIFRE TOTAL', 'lab');
	esc_html__('LabEx Archimède Genesis (Optis-Ansys)', 'lab');
	esc_html__('cotutelle AMU/FAPESP', 'lab');
	esc_html__('ECM/IRSN', 'lab');
	esc_html__('CONACyT', 'lab');
	esc_html__('ANR AIFIT', 'lab');
	esc_html__('B. Gouvt Algérien', 'lab');
	esc_html__('B. Gouvt Ivoirien', 'lab');
	esc_html__('LabEx Archimède', 'lab');
	esc_html__('CIFRE SEMM', 'lab');
	esc_html__('ED355', 'lab');
	esc_html__('Adjoint Technique (AJT)', 'lab');
	esc_html__('Détachement', 'lab');
	esc_html__('Disponibilité', 'lab');
	esc_html__('AMU (QUANTGMC)', 'lab');
	esc_html__('Enseignant-Chercheur Associé (PAST)', 'lab');
	esc_html__('IRSN Cadarache', 'lab');
	esc_html__('Attachée Temporaire d’Enseignement et de Recherche (ATER)', 'lab');
	esc_html__('Adjointe Technique de Recherche et de Formation (ATRF)', 'lab');
	esc_html__('Mutation', 'lab');
	esc_html__('Recrutement', 'lab');
	esc_html__('Promotion', 'lab');
	esc_html__('Changement de Groupe Scient.', 'lab');
	esc_html__('Démission', 'lab');
	esc_html__('Radiation', 'lab');
	esc_html__('Décès', 'lab');
	esc_html__('Retraite', 'lab');
	esc_html__('Éméritat', 'lab');
	esc_html__('Mise à Dispostion', 'lab');
	esc_html__('Délégation CNRS', 'lab');
	esc_html__('Annaba University (Algeria)', 'lab');
	esc_html__('26', 'lab');
	esc_html__('25', 'lab');
	esc_html__('27', 'lab');
	esc_html__('CDD Technicienne', 'lab');
	esc_html__('CDD Technicien', 'lab');
	esc_html__('CDD Ingénieur d\'Études', 'lab');
	esc_html__('CDD Ingénieure d\'Études', 'lab');
	esc_html__('CIFRE Resurgences R&D', 'lab');
	esc_html__('Agent Technique de Recherche et de Formation (AGT)', 'lab');
	esc_html__('Analysis and complex geometry', 'lab');
	esc_html__('Harmonic analysis', 'lab');
	esc_html__('Numerical analysis and scientific calculation', 'lab');
	esc_html__('Optimal control and inverse problems', 'lab');
	esc_html__('Cryptography', 'lab');
	esc_html__('Kinetic equations', 'lab');
	esc_html__('Elliptic PDE', 'lab');
	esc_html__('Hyperbolic PDE', 'lab');
	esc_html__('Parabolic PDE, population dynamics', 'lab');
	esc_html__('Algebraic geometry (null and positive characteristic)', 'lab');
	esc_html__('Differential geometry (including Lie groups, Riemannian, symplectic, etc.)', 'lab');
	esc_html__('History of mathematics', 'lab');
	esc_html__('Theoretical computer science, computability', 'lab');
	esc_html__('Logic', 'lab');
	esc_html__('Discrete mathematics', 'lab');
	esc_html__('Mathematics for Evolution and Biology', 'lab');
	esc_html__('Fluid mechanics', 'lab');
	esc_html__('Modelization, equations related to biology', 'lab');
	esc_html__('Probabilities', 'lab');
	esc_html__('Singularities', 'lab');
	esc_html__('Statistic', 'lab');
	esc_html__('Measured dynamic systems', 'lab');
	esc_html__('Geometric dynamic systems', 'lab');
	esc_html__('Symbolic dynamic systems', 'lab');
	esc_html__('Geometric group theory', 'lab');
	esc_html__('Algebraic number theory, arithmetic geometry', 'lab');
	esc_html__('Analytical number theory', 'lab');
	esc_html__('Theory of automorphic forms', 'lab');
	esc_html__('Operator theory', 'lab');
	esc_html__('Representation theory', 'lab');
	esc_html__('Topology (algebraic, low dimensional, general)', 'lab');
	esc_html__('Signal and image processing', 'lab');
	esc_html__('AMU/INSPE', 'lab');
	esc_html__('AMU (CENTURI)', 'lab');
	esc_html__('ED353', 'lab');
	esc_html__('AMU (ED353)', 'lab');
	esc_html__('ED352', 'lab');
	esc_html__('CIFRE ProGeLife', 'lab');
	esc_html__('CIFRE', 'lab');
	esc_html__('Collectivité territoriale', 'lab');
	esc_html__('B. Gouvt Libanais', 'lab');
	esc_html__('AMU (ED62)', 'lab');
	esc_html__('Adjoint Technique de Recherche et de Formation (ATRF)', 'lab');
	esc_html__('Directeur de Recherche Émérite (DREM)', 'lab');
	esc_html__('Ordinateur Apple', 'lab');
	esc_html__('Ordinateur Dell', 'lab');
	esc_html__('Consomable Apple', 'lab');
	esc_html__('Consomable Dell', 'lab');
	esc_html__('Consomable hors marché', 'lab');
	esc_html__('Maintenance serveur', 'lab');
	esc_html__('Professeur Émérite (PREM)', 'lab');
	esc_html__('Maintenance onduleur', 'lab');
	esc_html__('Option supplémentaire', 'lab');
	esc_html__('AMU', 'lab');
	esc_html__('CNRS', 'lab');
	esc_html__('ECM', 'lab');
	esc_html__('ANR', 'lab');
	esc_html__('ERC', 'lab');
	esc_html__('IUF', 'lab');
	esc_html__('PEPS', 'lab');
	esc_html__('PRC', 'lab');
	esc_html__('Autre', 'lab');
	esc_html__('Invitation', 'lab');
	esc_html__('Mission', 'lab');
	esc_html__('Membre Associé', 'lab');
	esc_html__('Train', 'lab');
	esc_html__('Plane', 'lab');
	esc_html__('Bike', 'lab');
	esc_html__('New', 'lab');
	esc_html__('Waiting group leader', 'lab');
	esc_html__('Waiting group manager', 'lab');
	esc_html__('Completed', 'lab');
	esc_html__('Validated by group leader', 'lab');
	esc_html__('Refused by group leader', 'lab');
	esc_html__('Cancelled', 'lab');
?>